### ISSUE TITLE
Why change from license to license-file?

### ISSUE THREAD

**Issue by ajorg-aws** [google/argh#101]
I saw 329890897aac903864c6b3e1672d8ce32a3ef5c3 "Use license-file to point at license" and it strikes me as a step backward, or rather at least removing the `license` attribute does. According to [the documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) (emphasis added):

> If a package is using _a nonstandard license_, then the license-file field _may_ be specified in lieu of the license field.

But this package is not using a nonstandard license. That doesn't seem to mean that we _cannot_ use `license-file` instead, but doing so means that we have to verify that LICENSE contains a standard license, and in some cases consider any variation.

Can both `license` _and_ `license-file` be used instead? And if not both, can the change be reverted so that we're not losing this important license information?

**Comment by erickt** [comment]
Ah, thanks for the reference, I now see I misunderstood `license-file`. I'll revert back to `license`.

**Comment by ajorg-aws** [comment]
Thank you!
