### ISSUE TITLE
Consider making serde dependency optional (as a feature)

### ISSUE THREAD

**Issue by grandchild** [google/argh#182]
First: Thanks for writing & publishing argh as libre software! It's been a joy to use and solves the problem without dependencies. Or at least it used to, hence this issue.

Where I'm coming from: I'm trying to keep my list of dependencies (and my binary size, but that's secondary) as small as possible for my (rust) programs.

My question: Would you consider putting the new serde dependency behind a feature flag? Then I could use argh without having another dependency to audit. Also it looks like my program would save a few bytes in binary size (although in all honesty the binary-size impact of serde seems rather minor, according to [`cargo bloat`](https://github.com/RazrFalcon/cargo-bloat)).

Thanks 🙂

**Comment by felipesere** [comment]
I'd also be interested in using argh without serde
