### ISSUE TITLE
Suggestion: `#[argh(rename = "name")]`

### ISSUE THREAD

**Issue by Boscop** [google/argh#28]
Problem: Often, fields that are option members have long (descriptive) names that make sense in the source code, but are too long to type for cli options. 
The attribute `short = 'x'` can only take single chars, so that can't be used to shorten them.

Solution: Adding a way to rename cli option members using `#[argh(rename = "name")]`.
Similar to `#[serde(rename = "name")]`.

**Comment by benbrittain** [comment]
I like this suggestion a lot! next time I hack on argh I'll do this :)

**Comment by trevarj** [comment]
Can't this already be done with overriding `long`?

```
struct Cmd {
     #[argh(option, long = "foo")]
     i_am_very_very_very_long: u8,
}
```

**Comment by Boscop** [comment]
@trevarj But that doesn't work to rename `positional` args. In `--help` they will still be printed with their rust field name.

**Comment by kafji** [comment]
Attribute field `arg_name` was added (#76) but it isn't honored for positional argument name.

I've submitted a patch to fix that. #104
