### ISSUE TITLE
Allow snake_case and kebab-case for `long` arg names

### ISSUE THREAD

**Issue by Boscop** [google/argh#34]
This should be allowed:

![image](https://user-images.githubusercontent.com/535593/86449859-0ab9c400-bd19-11ea-9065-860599e314ea.png)

Also underscore (snake_case) should be allowed in `long` names!

Maybe camelCase should be allowed, too.

**Comment by benbrittain** [comment]
The theory behind this is one should prefer sub commands to using multiple words in a long flag. This might be too aggressive of a lint though

**Comment by Boscop** [comment]
Thanks, I'd be happy if only kebab case is allowed :)

**Comment by benbrittain** [comment]
I overcautiously put spec-change-required here, but I think we can do this before any actual spec change
