### ISSUE TITLE
Not being able to do `--arg=value` is confusing

### ISSUE THREAD

**Issue by filmil** [google/argh#36]
The spec at https://fuchsia.dev/fuchsia-src/concepts/api/cli doesn't specifically say that `--arg=value` is disallowed, and yet argh disallows it.

While this may well be intended behavior, consider that it is a very confusing behavior for flags nowadays, where quite a few flag parsers assume `--arg value` and `--arg=value` can both work.  The latter works better in contexts where whitespaces can add
confusion.

**Comment by benbrittain** [comment]
Unfortunately, it is explicitly called out:

```Do not use an equals punctuation (or similar) to separate the key and value. E.g. do not do -o=<my_output_file>.```
