### ISSUE TITLE
Newline is missing in error output

### ISSUE THREAD

**Issue by hyd-dev** [google/argh#45]
I tried this:
```rust
#[derive(Clone, argh::FromArgs)]
#[argh(description = "...")]
struct Options {
    #[argh(option, description = "...")]
    bind_to: SocketAddr,
    #[argh(positional)]
    dir: PathBuf,
}
```

When I ran the program with no argument, it printed:
```
Required positional arguments not provided:
    dirRequired options not provided:
    --bind-to
```

The second line of the output was unreadable. I expected the output to be:
```
Required positional arguments not provided:
    dir
Required options not provided:
    --bind-to
```

It seems that https://github.com/google/argh/blob/507087f5367f47fb18a013f85d24b195d6c20bc3/src/lib.rs#L536-L538
is missing in https://github.com/google/argh/blob/507087f5367f47fb18a013f85d24b195d6c20bc3/src/lib.rs#L527-L529.

**Comment by siyopao** [comment]
If it is okay, I would like to try to fix this.

**Comment by benbrittain** [comment]
please do! It should be straightforward :)

I'll do the next argh release when you submit a PR
