### ISSUE TITLE
Usage message and errors should be printed to standard error

### ISSUE THREAD

**Issue by cole-miller** [google/argh#81]
Currently `EarlyExit` output is written to stdout, but stderr is more appropriate for diagnostics and any user-directed messages that should never end up in a pipeline.

**Comment by lassipulkkinen** [comment]
I would add that printing `--help` output to stdout does make sense, as the user might want to pipe it to `less` or something if they are using a terminal lacking a scrollback buffer. (This is what `clap` does IIRC.)
